package bean;
// Generated 08/10/2025 16:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DhmClientes generated by hbm2java
 */
@Entity
@Table(name="dhm_clientes"
    ,catalog="db_daniel_medeiros"
)
public class DhmClientes  implements java.io.Serializable {


     private int dhmIdCliente;
     private String dhmNome;
     private String dhmEmail;
     private String dhmBairro;
     private String dhmTelefone;
     private String dhmCidade;
     private String dhmCep;
     private String dhmRg;
     private String dhmEndereco;
     private String dhmCpf;
     private Date dhmDataNascimento;
     private Date dhmDataCadastro;
     private String dhmSenha;
     private String dhmAtivo;
     private String dhmNumero;
   

    public DhmClientes() {
    }

    
        public DhmClientes(int dhmIdCliente) {
this.dhmIdCliente = dhmIdCliente;
        }

    public DhmClientes(String dhmNome, String dhmEmail, String dhmBairro, String dhmTelefone, String dhmCidade, String dhmCep, String dhmRg, String dhmEndereco, String dhmCpf, Date dhmDataNascimento, Date dhmDataCadastro, String dhmSenha, String dhmAtivo, String dhmNumero) {
       this.dhmNome = dhmNome;
       this.dhmEmail = dhmEmail;
       this.dhmBairro = dhmBairro;
       this.dhmTelefone = dhmTelefone;
       this.dhmCidade = dhmCidade;
       this.dhmCep = dhmCep;
       this.dhmRg = dhmRg;
       this.dhmEndereco = dhmEndereco;
       this.dhmCpf = dhmCpf;
       this.dhmDataNascimento = dhmDataNascimento;
       this.dhmDataCadastro = dhmDataCadastro;
       this.dhmSenha = dhmSenha;
       this.dhmAtivo = dhmAtivo;
       this.dhmNumero = dhmNumero;
     
    }
   
     @Id 

    
    @Column(name="dhm_idCliente", unique=true, nullable=false)
    public int getDhmIdCliente() {
        return this.dhmIdCliente;
    }
    
    public void setDhmIdCliente(int dhmIdCliente) {
        this.dhmIdCliente = dhmIdCliente;
    }

    
    @Column(name="dhm_nome", length=100)
    public String getDhmNome() {
        return this.dhmNome;
    }
    
    public void setDhmNome(String dhmNome) {
        this.dhmNome = dhmNome;
    }

    
    @Column(name="dhm_email", length=100)
    public String getDhmEmail() {
        return this.dhmEmail;
    }
    
    public void setDhmEmail(String dhmEmail) {
        this.dhmEmail = dhmEmail;
    }

    
    @Column(name="dhm_bairro", length=50)
    public String getDhmBairro() {
        return this.dhmBairro;
    }
    
    public void setDhmBairro(String dhmBairro) {
        this.dhmBairro = dhmBairro;
    }

    
    @Column(name="dhm_telefone", length=20)
    public String getDhmTelefone() {
        return this.dhmTelefone;
    }
    
    public void setDhmTelefone(String dhmTelefone) {
        this.dhmTelefone = dhmTelefone;
    }

    
    @Column(name="dhm_cidade", length=50)
    public String getDhmCidade() {
        return this.dhmCidade;
    }
    
    public void setDhmCidade(String dhmCidade) {
        this.dhmCidade = dhmCidade;
    }

    
    @Column(name="dhm_cep", length=10)
    public String getDhmCep() {
        return this.dhmCep;
    }
    
    public void setDhmCep(String dhmCep) {
        this.dhmCep = dhmCep;
    }

    
    @Column(name="dhm_rg", length=20)
    public String getDhmRg() {
        return this.dhmRg;
    }
    
    public void setDhmRg(String dhmRg) {
        this.dhmRg = dhmRg;
    }

    
    @Column(name="dhm_endereco", length=100)
    public String getDhmEndereco() {
        return this.dhmEndereco;
    }
    
    public void setDhmEndereco(String dhmEndereco) {
        this.dhmEndereco = dhmEndereco;
    }

    
    @Column(name="dhm_cpf", length=14)
    public String getDhmCpf() {
        return this.dhmCpf;
    }
    
    public void setDhmCpf(String dhmCpf) {
        this.dhmCpf = dhmCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dhm_data_nascimento", length=10)
    public Date getDhmDataNascimento() {
        return this.dhmDataNascimento;
    }
    
    public void setDhmDataNascimento(Date dhmDataNascimento) {
        this.dhmDataNascimento = dhmDataNascimento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dhm_data_cadastro", length=10)
    public Date getDhmDataCadastro() {
        return this.dhmDataCadastro;
    }
    
    public void setDhmDataCadastro(Date dhmDataCadastro) {
        this.dhmDataCadastro = dhmDataCadastro;
    }

    
    @Column(name="dhm_senha", length=100)
    public String getDhmSenha() {
        return this.dhmSenha;
    }
    
    public void setDhmSenha(String dhmSenha) {
        this.dhmSenha = dhmSenha;
    }

    
    @Column(name="dhm_ativo", length=1)
    public String getDhmAtivo() {
        return this.dhmAtivo;
    }
    
    public void setDhmAtivo(String dhmAtivo) {
        this.dhmAtivo = dhmAtivo;
    }

    
    @Column(name="dhm_numero", length=20)
    public String getDhmNumero() {
        return this.dhmNumero;
    }
    
    public void setDhmNumero(String dhmNumero) {
        this.dhmNumero = dhmNumero;
    }


@Override
    public String toString() {
        return this.dhmNome;
    }
}


