package bean;
// Generated 08/10/2025 16:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DhmProdutos generated by hbm2java
 */
@Entity
@Table(name="dhm_produtos"
    ,catalog="db_daniel_medeiros"
)
public class DhmProdutos  implements java.io.Serializable {


     private int dhmIdProduto;
     private String dhmDescricao;
     private double dhmPreco;
     private String dhmCategoria;
     private int dhmEstoque;
     private String dhmMarca;
     private String dhmNome;
 

    public DhmProdutos() {
    }

    public DhmProdutos(String dhmDescricao, double dhmPreco, String dhmCategoria, int dhmEstoque, String dhmMarca, String dhmNome) {
       this.dhmDescricao = dhmDescricao;
       this.dhmPreco = dhmPreco;
       this.dhmCategoria = dhmCategoria;
       this.dhmEstoque = dhmEstoque;
       this.dhmMarca = dhmMarca;
       this.dhmNome = dhmNome;
        }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="dhm_idProduto", unique=true, nullable=false)
    public int getDhmIdProduto() {
        return this.dhmIdProduto;
    }
    
    public void setDhmIdProduto(int dhmIdProduto) {
        this.dhmIdProduto = dhmIdProduto;
    }

    
    @Column(name="dhm_descricao", length=200)
    public String getDhmDescricao() {
        return this.dhmDescricao;
    }
    
    public void setDhmDescricao(String dhmDescricao) {
        this.dhmDescricao = dhmDescricao;
    }

    
    @Column(name="dhm_preco", precision=10)
    public double getDhmPreco() {
        return this.dhmPreco;
    }
    
    public void setDhmPreco(double dhmPreco) {
        this.dhmPreco = dhmPreco;
    }

    
    @Column(name="dhm_categoria", length=50)
    public String getDhmCategoria() {
        return this.dhmCategoria;
    }
    
    public void setDhmCategoria(String dhmCategoria) {
        this.dhmCategoria = dhmCategoria;
    }

    
    @Column(name="dhm_estoque")
    public int getDhmEstoque() {
        return this.dhmEstoque;
    }
    
    public void setDhmEstoque(int dhmEstoque) {
        this.dhmEstoque = dhmEstoque;
    }

    
    @Column(name="dhm_marca", length=50)
    public String getDhmMarca() {
        return this.dhmMarca;
    }
    
    public void setDhmMarca(String dhmMarca) {
        this.dhmMarca = dhmMarca;
    }

    
    @Column(name="dhm_nome", length=100)
    public String getDhmNome() {
        return this.dhmNome;
    }
    
    public void setDhmNome(String dhmNome) {
        this.dhmNome = dhmNome;
    }


}


