package bean;
// Generated 08/10/2025 16:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DhmUsuarios generated by hbm2java
 */
@Entity
@Table(name="dhm_usuarios"
    ,catalog="db_daniel_medeiros"
)
public class DhmUsuarios  implements java.io.Serializable {


     private int dhmIdUsuario;
     private String dhmNome;
     private Date dhmDataNascimento;
     private String dhmApelido;
     private String dhmSenha;
     private String dhmCpf;
     private int dhmNivel;
     private String dhmAtivo;

    public DhmUsuarios() {
    }

    public DhmUsuarios(int dhmIdUsuario,String dhmNome, Date dhmDataNascimento, String dhmApelido, String dhmSenha, String dhmCpf, int dhmNivel, String dhmAtivo) {
       this.dhmIdUsuario = dhmIdUsuario;
        this.dhmNome = dhmNome;
       this.dhmDataNascimento = dhmDataNascimento;
       this.dhmApelido = dhmApelido;
       this.dhmSenha = dhmSenha;
       this.dhmCpf = dhmCpf;
       this.dhmNivel = dhmNivel;
       this.dhmAtivo = dhmAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="dhm_idUsuario", unique=true, nullable=false)
    public int getDhmIdUsuario() {
        return this.dhmIdUsuario;
    }
    
    public void setDhmIdUsuario(int dhmIdUsuario) {
        this.dhmIdUsuario = dhmIdUsuario;
    }

    
    @Column(name="dhm_Nome", length=100)
    public String getDhmNome() {
        return this.dhmNome;
    }
    
    public void setDhmNome(String dhmNome) {
        this.dhmNome = dhmNome;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dhm_Data_Nascimento", length=10)
    public Date getDhmDataNascimento() {
        return this.dhmDataNascimento;
    }
    
    public void setDhmDataNascimento(Date dhmDataNascimento) {
        this.dhmDataNascimento = dhmDataNascimento;
    }

    
    @Column(name="dhm_Apelido", length=20)
    public String getDhmApelido() {
        return this.dhmApelido;
    }
    
    public void setDhmApelido(String dhmApelido) {
        this.dhmApelido = dhmApelido;
    }

    
    @Column(name="dhm_Senha", length=100)
    public String getDhmSenha() {
        return this.dhmSenha;
    }
    
    public void setDhmSenha(String dhmSenha) {
        this.dhmSenha = dhmSenha;
    }

    
    @Column(name="dhm_Cpf", length=14)
    public String getDhmCpf() {
        return this.dhmCpf;
    }
    
    public void setDhmCpf(String dhmCpf) {
        this.dhmCpf = dhmCpf;
    }

    
    @Column(name="dhm_Nivel")
    public int getDhmNivel() {
        return this.dhmNivel;
    }
    
    public void setDhmNivel(int dhmNivel) {
        this.dhmNivel = dhmNivel;
    }

    
    @Column(name="dhm_Ativo", length=1)
    public String getDhmAtivo() {
        return this.dhmAtivo;
    }
    
    public void setDhmAtivo(String dhmAtivo) {
        this.dhmAtivo = dhmAtivo;
    }




}