package bean;
// Generated 08/10/2025 16:36:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DhmVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="dhm_vendas_produtos"
    ,catalog="db_daniel_medeiros"
)
public class DhmVendasProdutos  implements java.io.Serializable {


     private int dhmIdVendasProdutos;
     private DhmProdutos dhmProdutos;
     private DhmVendas dhmVendas;
     private int dhmQuantidade;
     private double dhmValorUnitario;

    public DhmVendasProdutos() {
    }

    public DhmVendasProdutos(int dhmIdVendasProdutos, DhmProdutos dhmProdutos, DhmVendas dhmVendas, int dhmQuantidade, double dhmValorUnitario) {
       this.dhmIdVendasProdutos = dhmIdVendasProdutos;
       this.dhmProdutos = dhmProdutos;
       this.dhmVendas = dhmVendas;
       this.dhmQuantidade = dhmQuantidade;
       this.dhmValorUnitario = dhmValorUnitario;
    }
   
     @Id 

    
    @Column(name="dhm_idVendasProdutos", unique=true, nullable=false)
    public int getDhmIdVendasProdutos() {
        return this.dhmIdVendasProdutos;
    }
    
    public void setDhmIdVendasProdutos(int dhmIdVendasProdutos) {
        this.dhmIdVendasProdutos = dhmIdVendasProdutos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="dhm_fkProdutos", nullable=false)
    public DhmProdutos getDhmProdutos() {
        return this.dhmProdutos;
    }
    
    public void setDhmProdutos(DhmProdutos dhmProdutos) {
        this.dhmProdutos = dhmProdutos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="dhm_fkVendas", nullable=false)
    public DhmVendas getDhmVendas() {
        return this.dhmVendas;
    }
    
    public void setDhmVendas(DhmVendas dhmVendas) {
        this.dhmVendas = dhmVendas;
    }

    
    @Column(name="dhm_quantidade", nullable=false)
    public int getDhmQuantidade() {
        return this.dhmQuantidade;
    }
    
    public void setDhmQuantidade(int dhmQuantidade) {
        this.dhmQuantidade = dhmQuantidade;
    }

    
    @Column(name="dhm_valorUnitario", nullable=false, precision=10)
    public double getDhmValorUnitario() {
        return this.dhmValorUnitario;
    }
    
    public void setDhmValorUnitario(double dhmValorUnitario) {
        this.dhmValorUnitario = dhmValorUnitario;
    }




}


