package bean;
// Generated 08/10/2025 16:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DhmVendedor generated by hbm2java
 */
@Entity
@Table(name="dhm_vendedor"
    ,catalog="db_daniel_medeiros"
    , uniqueConstraints = @UniqueConstraint(columnNames="dhm_cpf") 
)
public class DhmVendedor  implements java.io.Serializable {


     private int dhmIdVendedor;
     private String dhmNome;
     private String dhmCpf;
     private String dhmEmail;
     private String dhmTelefone;
     private double dhmSalario;
   

    public DhmVendedor() {
    }
 public DhmVendedor(int dhmIdVendedor) {
this.dhmIdVendedor = dhmIdVendedor;
        }

	

    public DhmVendedor(int dhmIdVendedor, String dhmNome, String dhmCpf, String dhmEmail, String dhmTelefone, double dhmSalario) {
      this.dhmIdVendedor = dhmIdVendedor;
       this.dhmNome = dhmNome;
       this.dhmCpf = dhmCpf;
       this.dhmEmail = dhmEmail;
       this.dhmTelefone = dhmTelefone;
       this.dhmSalario = dhmSalario;
      
    }
   
     @Id

    
    @Column(name="dhm_id_vendedor", unique=true, nullable=false)
    public int getDhmIdVendedor() {
        return this.dhmIdVendedor;
    }
    
    public void setDhmIdVendedor(int dhmIdVendedor) {
        this.dhmIdVendedor = dhmIdVendedor;
    }

    
    @Column(name="dhm_nome", nullable=false, length=100)
    public String getDhmNome() {
        return this.dhmNome;
    }
    
    public void setDhmNome(String dhmNome) {
        this.dhmNome = dhmNome;
    }

    
    @Column(name="dhm_cpf", unique=true, nullable=false, length=14)
    public String getDhmCpf() {
        return this.dhmCpf;
    }
    
    public void setDhmCpf(String dhmCpf) {
        this.dhmCpf = dhmCpf;
    }

    
    @Column(name="dhm_email", length=100)
    public String getDhmEmail() {
        return this.dhmEmail;
    }
    
    public void setDhmEmail(String dhmEmail) {
        this.dhmEmail = dhmEmail;
    }

    
    @Column(name="dhm_telefone", length=20)
    public String getDhmTelefone() {
        return this.dhmTelefone;
    }
    
    public void setDhmTelefone(String dhmTelefone) {
        this.dhmTelefone = dhmTelefone;
    }

    
    @Column(name="dhm_salario", nullable=false, precision=10)
    public double getDhmSalario() {
        return this.dhmSalario;
    }
    
    public void setDhmSalario(double dhmSalario) {
        this.dhmSalario = dhmSalario;
    }

    
    
@Override
    public String toString() {
        return this.dhmNome;
    }
}


