package bean;
// Generated 08/10/2025 16:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DhmVendas generated by hbm2java
 */
@Entity
@Table(name="dhm_vendas"
    ,catalog="db_daniel_medeiros"
)
public class DhmVendas  implements java.io.Serializable {


     private int dhmIdVendas;
     private DhmClientes dhmClientes;
     private DhmVendedor dhmVendedor;
     private double dhmTotal;
     private Date dhmDataPedido;
   

    public DhmVendas() {
    }

	
    public DhmVendas(double dhmTotal, Date dhmDataPedido) {
        this.dhmTotal = dhmTotal;
        this.dhmDataPedido = dhmDataPedido;
    }
    public DhmVendas(DhmClientes dhmClientes, DhmVendedor dhmVendedor, double dhmTotal, Date dhmDataPedido) {
       this.dhmClientes = dhmClientes;
       this.dhmVendedor = dhmVendedor;
       this.dhmTotal = dhmTotal;
       this.dhmDataPedido = dhmDataPedido;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="dhm_IdVendas", unique=true, nullable=false)
    public int getDhmIdVendas() {
        return this.dhmIdVendas;
    }
    
    public void setDhmIdVendas(int dhmIdVendas) {
        this.dhmIdVendas = dhmIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dhm_fkCliente")
    public DhmClientes getDhmClientes() {
        return this.dhmClientes;
    }
    
    public void setDhmClientes(DhmClientes dhmClientes) {
        this.dhmClientes = dhmClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dhm_fkVendedor")
    public DhmVendedor getDhmVendedor() {
        return this.dhmVendedor;
    }
    
    public void setDhmVendedor(DhmVendedor dhmVendedor) {
        this.dhmVendedor = dhmVendedor;
    }

    
    @Column(name="dhm_Total", nullable=false, precision=10)
    public double getDhmTotal() {
        return this.dhmTotal;
    }
    
    public void setDhmTotal(double dhmTotal) {
        this.dhmTotal = dhmTotal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dhm_DataPedido", nullable=false, length=10)
    public Date getDhmDataPedido() {
        return this.dhmDataPedido;
    }
    
    public void setDhmDataPedido(Date dhmDataPedido) {
        this.dhmDataPedido = dhmDataPedido;
    }





}


